site_name: Deezer

site_favicon: assets/favicon.ico

nav:
    - Inicial: index.md
    - Planejamento: planejamento.md
    - Pré-rastreabilidade:
        - Sobre: pre-rastreabilidade/pre_rastreabilidade.md
        - Backward-from: pre-rastreabilidade/backward_from.md 
        - Rich Pictures: pre-rastreabilidade/rich-pictures.md
        - Ponto de Controle: pontocontrole.md
    - Elicitação:
        - MoScoW: elicitacao/moscow1.md
        - Introspecção: elicitacao/introspeccao.md
        - Observação Participativa: elicitacao/obs_part.md
        - Análise de Protocolo: elicitacao/analise_de_protocolo.md
        - Questionário: elicitacao/questionario2.md
        - Entrevista: elicitacao/entrevista.md
    - Modelagem:
        - Cenários: modelagem/cenarios/cenarios.md
        - Léxico: modelagem/lexico.md
        - Especificação Suplementar: modelagem/especificacao_suplementar.md
        - Casos de Uso: modelagem/caso_de_uso.md
        - Diagramas de Caso de Uso: modelagem/diagrama_caso_uso.md
        - Histórias de Usuário: modelagem/historia_de_usuario.md
        - NFR: modelagem/nfr.md
    - Análise:
        - Verificação: analise/verificacao.md
        - Validação: analise/validacaoprototipo.md
    - Pós-rastreabilidade:
        - Sobre: pos-rastreabilidade/pos_rastreabilidade.md
        - Forward-from: pos-rastreabilidade/forward_from.md 

        
theme: readthedocs

extra_css:
    - 'stylesheets/common.css'
